Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogStream"
                  - "logs:CreateLogGroup"
                Resource:
                  - "arn:aws:logs:eu-west-2:${env:AWS_ACCOUNT_ID}:log-group:/aws/lambda/alchelign*:*"
              - Effect: Allow
                Action:
                  - "logs:PutLogEvents"
                Resource:
                  - "arn:aws:logs:eu-west-2:${env:AWS_ACCOUNT_ID}:log-group:/aws/lambda/alchelign*:*:*"
              - Effect: Allow
                Action:
                  - "cognito-idp:AdminListGroupsForUser"
                Resource:
                  - "${env:COGNITO_USER_POOL_ARN}"
              - Effect: Allow
                Action:
                  - "ec2:CreateNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DeleteNetworkInterface"
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - "s3:ListAllMyBuckets"
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:ListBucketVersions"
                  - "s3:GetBucketLocation"
                Resource:
                  - "arn:aws:s3:::alchelign-*"
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:GetObject"
                  - "s3:GetObjectAcl"
                  - "s3:DeleteObject"
                  - "s3:ListObjectVersions"
                  - "s3:GetObjectVersion"
                  - "s3-object-lambda:PutObject"
                  - "s3-object-lambda:PutObjectAcl"
                  - "s3-object-lambda:Get*"
                  - "s3-object-lambda:List*"
                Resource:
                  - "arn:aws:s3:::alchelign-*/*"
                  - "arn:aws:s3:::alchelign-*"
