// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
  aws_project_region: import.meta.env.VITE_AWS_REGION,
  aws_cognito_region: import.meta.env.VITE_AWS_REGION,
  aws_user_pools_id: import.meta.env.VITE_AWS_POOL_ID,
  aws_user_pools_web_client_id: import.meta.env.VITE_USER_POOL_WEB_CLIENT_ID,
  oauth: {
    domain: import.meta.env.VITE_OAUTH_DOMAIN,
    scope: ["email", "openid", "profile", "aws.cognito.signin.user.admin"],
    redirectSignIn: import.meta.env.VITE_OAUTH_REDIRECT_SIGN_IN,
    redirectSignOut: import.meta.env.VITE_OAUTH_REDIRECT_SIGN_IN,
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
};
console.log(import.meta.env);
export default awsconfig;
